image:
  repository: registry.ereslibre.net/kubewarden/kubewarden-controller
  tag: latest
policyServer:
  image:
    repository: registry.ereslibre.net/kubewarden/policy-server
    tag: latest
  env:
  - name: KUBEWARDEN_LOG_LEVEL
    value: info
  - name: KUBEWARDEN_LOG_FMT
    value: otlp
  - name: KUBEWARDEN_ENABLE_METRICS
    value: "1"
  annotations:
    sidecar.opentelemetry.io/inject: "true"
