prometheus:
  additionalServiceMonitors:
    - name: kubewarden
      selector:
        matchLabels:
          app: kubewarden-policy-server-ha-policy-server
      namespaceSelector:
        matchNames:
        - kubewarden
      endpoints:
        - port: metrics
          interval: 10s
